version: '3'
services:
  textstore-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - ./semaphores:/app/semaphore
    environment:
     - MONGO_DB=mongodb://mongodb:27017/textstore
     - ACCESS_TOKEN_SECRET=averysecrettoken
     - BLOOM_FILTER_SIZE=1024
  mongodb:
    image: ghcr.io/ferretdb/all-in-one
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
  mongo-express:
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_BASICAUTH_USERNAME=adminlogin
        - ME_CONFIG_BASICAUTH_PASSWORD=Veryadminned
    depends_on:
        - mongodb
    links:
        - mongodb
    ports:
      - "8081:8081"
volumes:
  mongo-data:
  semaphores:
